import {
  BILLING_UPGRADE_URL,
  DEFAULT_BASE_URL,
  DEFAULT_LIVE_WINDOW_SECONDS,
  DEFAULT_POLL_INTERVAL_SECONDS,
} from '../shared/constants.js';

const now = Date.now();

export const demoLiveState = {
  type: 'live_state',
  generatedAt: now,
  pluginEnabled: true,
  authStatus: 'connected',
  tier: 'pro',
  account: {
    id: 'acct_demo',
    email: 'operator@example.com',
    githubLogin: 'operator',
    googleName: 'Operator Demo',
  },
  connection: {
    status: 'live',
    label: 'Live now',
    detail: 'Showing live state for agentanalytics-sh.',
    reason: 'live_active',
  },
  metrics: {
    activeVisitors: 12,
    activeSessions: 14,
    eventsPerMinute: 30,
    assetsConfigured: 1,
    assetsVisible: 1,
    countriesTracked: 5,
  },
  world: {
    hotCountry: 'US',
    countries: [
      { country: 'US', visitors: 12, sessions: 13, events: 31 },
      { country: 'DE', visitors: 5, sessions: 6, events: 13 },
      { country: 'GB', visitors: 4, sessions: 5, events: 11 },
      { country: 'IN', visitors: 4, sessions: 5, events: 10 },
      { country: 'IL', visitors: 4, sessions: 5, events: 6 },
    ],
  },
  evidence: {
    topPages: [
      { path: '/pricing', visitors: 12 },
      { path: '/docs/installation', visitors: 8 },
      { path: '/signup', visitors: 5 },
    ],
    topEvents: [
      { event: 'page_view', count: 44 },
      { event: 'signup', count: 12 },
      { event: 'api_key_created', count: 5 },
    ],
    recentEvents: [
      {
        id: 'evt_1',
        event: 'signup',
        path: '/signup',
        country: 'US',
        userId: 'anon_a12',
        sessionId: 'sess_1',
        timestamp: now - 15_000,
        assetKey: 'marketing-site',
        assetLabel: 'Marketing Site',
      },
      {
        id: 'evt_2',
        event: 'page_view',
        path: '/docs/installation',
        country: 'DE',
        userId: 'anon_a18',
        sessionId: 'sess_2',
        timestamp: now - 32_000,
        assetKey: 'agentanalytics-sh',
        assetLabel: 'agentanalytics-sh',
      },
      {
        id: 'evt_3',
        event: 'api_key_created',
        path: '/settings/api',
        country: 'GB',
        userId: 'anon_a20',
        sessionId: 'sess_3',
        timestamp: now - 44_000,
        assetKey: 'agentanalytics-sh',
        assetLabel: 'agentanalytics-sh',
      },
    ],
    countries: [
      { country: 'US', visitors: 12, sessions: 13, events: 31 },
      { country: 'DE', visitors: 5, sessions: 6, events: 13 },
      { country: 'GB', visitors: 4, sessions: 5, events: 11 },
    ],
  },
  assets: [
    {
      assetKey: 'agentanalytics-sh',
      label: 'agentanalytics-sh',
      kind: 'other',
      paperclipProjectId: '',
      agentAnalyticsProject: 'agentanalytics-sh',
      primaryHostname: '',
      enabled: true,
      status: 'live',
      lastUpdatedAt: now,
      lastSnapshotAt: now - 15_000,
      lastPolledAt: now - 9_000,
      lastHotCountry: 'US',
      activeVisitors: 12,
      activeSessions: 14,
      eventsPerMinute: 30,
      topPages: [
        { path: '/pricing', visitors: 8 },
        { path: '/', visitors: 4 },
      ],
      topEvents: [
        { event: 'page_view', count: 21 },
        { event: 'signup', count: 6 },
      ],
      countries: [
        { country: 'US', visitors: 6, sessions: 7, events: 15 },
        { country: 'IN', visitors: 3, sessions: 4, events: 7 },
      ],
      recentEvents: [],
      warnings: [],
      errors: [],
    },
  ],
  historicalSummary: {
    projectId: 'aa_marketing',
    projectName: 'agentanalytics-sh',
    projectLabel: 'agentanalytics-sh',
    allowedOrigins: ['*'],
    usageToday: { events: 42, reads: 3 },
    totals: { events: 186, reads: 12 },
    activeDays: 5,
    lastActiveDate: new Date(now - 86_400_000).toISOString().slice(0, 10),
    windowDays: 7,
    sparkline: Array.from({ length: 7 }, (_, index) => ({
      date: new Date(now - (6 - index) * 86_400_000).toISOString().slice(0, 10),
      events: [8, 0, 24, 31, 46, 35, 42][index],
      reads: 0,
    })),
    hasActivity: true,
  },
  snoozedAssets: [],
  warnings: [],
};

export const demoSettingsData = {
  settings: {
    agentAnalyticsBaseUrl: DEFAULT_BASE_URL,
    liveWindowSeconds: DEFAULT_LIVE_WINDOW_SECONDS,
    pollIntervalSeconds: DEFAULT_POLL_INTERVAL_SECONDS,
    pluginEnabled: true,
    selectedProjectId: 'aa_marketing',
    selectedProjectName: 'agentanalytics-sh',
    selectedProjectLabel: 'agentanalytics-sh',
    selectedProjectAllowedOrigins: ['*'],
    monitoredAssets: [],
  },
  auth: {
    status: 'connected',
    mode: 'agent_session',
    tier: 'pro',
    accountSummary: demoLiveState.account,
    accessExpiresAt: now + 3_600_000,
    refreshExpiresAt: now + 7_200_000,
    pendingAuthRequest: null,
    lastValidatedAt: now,
    lastError: null,
    connected: true,
  },
  discoveredProjects: [
    { id: 'aa_marketing', name: 'agentanalytics-sh', allowed_origins: '*' },
    { id: 'aa_docs', name: 'docs-agentanalytics-sh', allowed_origins: '*' },
    { id: 'aa_app', name: 'app-agentanalytics-sh', allowed_origins: '*' },
  ],
  validation: {
    warnings: [
      `Live events are a paid feature. Upgrade at ${BILLING_UPGRADE_URL} if this account is on the free tier.`,
    ],
    errors: [],
  },
  projectListError: null,
};
